export const product = [
  {
    id: '1',
    name: 'Hollow Cement Block',
    size: '20*20*40 CM',
    price: '$20',
    image: 'assets/images/block1.jpeg',
  },
  {
    id: '2',
    name: 'Hollow Cement Block',
    size: '15*20*20 CM',
    price: '$18',
    image: 'assets/images/block3.jpeg',
  },
  {
    id: '3',
    name: 'Hollow Cement Block',
    size: '10*10*20 CM',
    price: '$15',
    image: 'assets/images/block2.jpeg',
  },
  {
    id: '4',
    name: 'Fluted Cement Block',
    size: '20*20*40 CM',
    price: '$25',
    image: 'assets/images/block4.jpeg',
  },
  {
    id: '5',
    name: 'Fluted Cement Block',
    size: '10*10*20 CM',
    price: '$23',
    image: 'assets/images/block8.jpeg',
  },
  {
    id: '6',
    name: 'Solid Cement Block',
    size: '20*20*40 CM',
    price: '$28',
    image: 'assets/images/block6.jpeg',
  },
  {
    id: '7',
    name: 'Solid Cement Block',
    size: '15*20*20 CM',
    price: '$26',
    image: 'assets/images/block5.jpeg',
  },
  {
    id: '8',
    name: 'Solid Cement Block',
    size: '10*20*20 CM',
    price: '$17',
    image: 'assets/images/block7.jpeg',
  },
  {
    id: '9',
    name: 'Hourdy Cement Block',
    size: '40*20*20*38 CM',
    price: '$30',
    image: 'assets/images/block10.jpeg',
  },
  {
    id: '10',
    name: 'Hourdy Cement Block',
    size: '40*20*25*38 CM',
    price: '$28',
    image: 'assets/images/block9.jpeg',
  },
  {
    id: '11',
    name: 'Insulated Block',
    size: '20*20*40 CM',
    price: '$24',
    image: 'assets/images/block12.jpeg',
  },
  {
    id: '12',
    name: 'Insulated Block',
    size: '10*10*40 CM',
    price: '$14',
    image: 'assets/images/block11.jpeg',
  },
  {
    id: '13',
    size: '',
    name: '3/8 AGGREGATE',
    price: '$34',
    image: 'assets/images/S1.jpeg',
  },
  {
    id: '14',
    size: '',
    name: '3/16 AGGREGATE',
    price: '$23',
    image: 'assets/images/S3.jpeg',
  },
  {
    id: '15',
    size: '',
    name: '1/2 AGGREGATE',
    price: '$22',
    image: 'assets/images/S2.jpeg',
  },
  {
    id: '16',
    size: '',
    name: '3/4 AGGREGATE',
    price: '$15',
    image: 'assets/images/S4.jpeg',
  },

  {
    id: '17',
    size: '',
    name: 'Precast Concrete',
    price: '$54',
    image: 'assets/images/kh3.jpg',
  },
  {
    id: '18',
    size: '',
    name: 'Prestressed Concrete',
    price: '$56',
    image: 'assets/images/kh4.jpg',
  },
  {
    id: '19',
    size: '',
    name: 'Plain Concrete',
    price: '$65',
    image: 'assets/images/C5.jpeg',
  },
  {
    id: '20',
    size: '',
    name: 'Normal Strength Concrete',
    price: '$46',
    image: 'assets/images/C6.jpeg',
  },
  {
    id: '21',
    size: '',
    name: 'Reinforced Concrete',
    price: '$39',
    image: 'assets/images/C7.jpeg',
  },
  {
    id: '22',
    size: '',
    name: 'High-Density Concrete',
    price: '$61',
    image: 'assets/images/C1.jpeg',
  },
  {
    id: '23',
    size: '',
    name: 'Stamped Concrete',
    price: '$55',
    image: 'assets/images/kh1.jpg',
  },
  {
    id: '24',
    size: '',
    name: 'Glass Concrete',
    price: '$65',
    image: 'assets/images/kh2.jpg',
  },
];
