export const product = [
  {
    id: '1',
    name: 'Hollow Cement Block',
    size: '20*20*40 CM',
    price: '$20',
    image: 'assets/images/block1.jpeg',
  },
  {
    id: '2',
    name: 'Hollow Cement Block',
    size: '15*20*20 CM',
    price: '$18',
    image: 'assets/images/block3.jpeg',
  },
  {
    id: '3',
    name: 'Hollow Cement Block',
    size: '10*10*20 CM',
    price: '$15',
    image: 'assets/images/block2.jpeg',
  },
  {
    id: '4',
    name: 'Fluted Cement Block',
    size: '20*20*40 CM',
    price: '$25',
    image: 'assets/images/block4.jpeg',
  },
  {
    id: '5',
    name: 'Fluted Cement Block',
    size: '10*10*20 CM',
    price: '$23',
    image: 'assets/images/block8.jpeg',
  },
  {
    id: '6',
    name: 'Solid Cement Block',
    size: '20*20*40 CM',
    price: '$28',
    image: 'assets/images/block6.jpeg',
  },
  {
    id: '7',
    name: 'Solid Cement Block',
    size: '15*20*20 CM',
    price: '$26',
    image: 'assets/images/block5.jpeg',
  },
  {
    id: '8',
    name: 'Solid Cement Block',
    size: '10*20*20 CM',
    price: '$17',
    image: 'assets/images/block7.jpeg',
  },
  {
    id: '9',
    name: 'Hourdy Cement Block',
    size: '40*20*20*38 CM',
    price: '$30',
    image: 'assets/images/block10.jpeg',
  },
  {
    id: '10',
    name: 'Hourdy Cement Block',
    size: '40*20*25*38 CM',
    price: '$28',
    image: 'assets/images/block9.jpeg',
  },
  {
    id: '11',
    name: 'Insulated Block',
    size: '20*20*40 CM',
    price: '$24',
    image: 'assets/images/block12.jpeg',
  },
  {
    id: '12',
    name: 'Insulated Block',
    size: '10*10*40 CM',
    price: '$14',
    image: 'assets/images/block11.jpeg',
  },
];
